Inverted Index Application Update
andela-aatanda/checkpoint1-inverted-index pull request #4
Opened 2016-11-03 16:01 UTC by andela-aatanda

### What this PR do?
Implement feedback from PR #1 

### How to manually test this PR?
Check Files changed

2016-11-14 16:05 UTC, q-ode requested changes
Kindly go through the AirBnB Style Guide once again and see that you conform to these recommendations.
https://github.com/airbnb/javascript

2016-11-14 16:05 UTC, q-ode commented on src/inverted-index.js
> +
Empty line here...

2016-11-14 16:05 UTC, q-ode commented on src/inverted-index.js
> +
Empty line...

2016-11-14 16:05 UTC, q-ode commented on src/inverted-index.js
> +      for (let i = 0; i < file.length; i++) {
Nitpick: What is i?

2016-11-14 16:05 UTC, q-ode commented on src/inverted-index.js
> +
Empty space...

2016-11-14 16:05 UTC, q-ode commented on src/inverted-index.js
> +
Space...

2016-11-14 16:05 UTC, q-ode commented on src/pageCtrl.js
> +
Space...

2016-11-14 16:05 UTC, q-ode commented on src/pageCtrl.js
> +    return false;
Not properly indented.

2016-11-14 16:05 UTC, q-ode commented on src/inverted-index.js
> +    else {
AirBnB Style Guide: `put else on the same line as your if block's closing`

2016-11-14 19:02 UTC, andela-aatanda commented on src/pageCtrl.js
> +
@q-ode I was following the space after every block rule of Airbnb

2016-11-17 22:00 UTC, q-ode requested changes
Hey man,
Kindly attend to the changes and reach out to me if you need further clarification. 

PS: Why is your setup of HoundCI throwing so many errors?

2016-11-17 22:00 UTC, q-ode commented on src/pageCtrl.js
> +const isJson = (term) => {
Is this supposed to be a utility function?
If so, it shouldn't be here. Also, why are you declaring functions as `const`?

2016-11-17 22:00 UTC, q-ode commented on src/inverted-index.js
> +const tokenize = (tokens) => {
I believe you're trying to declare a class function here.

Firstly, it shouldn't be outside the class.

Secondly, why are you declaring functions with the keyword `const`?

2016-11-17 22:00 UTC, q-ode commented on src/inverted-index.js
> +  return newToken;
The variable `newToken` is redundant here. You're declaring it just to return the value.

What do you think about returning said value directly?

2016-11-17 22:00 UTC, q-ode commented on src/inverted-index.js
> +        result[key] = value;
The use of variable `value` is redundant here as you only initialized it in the line above just to pass the value to this line.

2016-11-21 08:55 UTC, merged